site_name: Urban Observatory API (uoapi) Documentation
theme:
  name: 'readthedocs'
  hljs_languages:
    - yaml
    - python
    - bash
    - json
    - markdown
  color_mode: dark
nav:
  - Home: index.md
  - Installation: installation.md
  - API Client: client.md

# GitHub Pages
repo_url: https://github.com/carrowmw/uoapi
repo_name: uoapi
site_url: https://carrowmw.github.io/uoapi/